-- Date Functions
--
-- Get discovery date data
-- from the object table in the space schema.
-- The result must contain four columns:
-- name;
-- the d_year column,
-- which contains the year of the object's discovery;
-- the d_month column,
-- which contains the name of the month
-- of the object's discovery;
-- the d_day column,
-- which contains the name of the weekday
-- of the object's discovery.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Функції дати
--
-- Отримай з таблиці object,
-- схема space,
-- дані про дату відкриття.
-- Результат повинен містити чотири колонки:
-- name;
-- колонку d_year,
-- що містить рік відкриття об'єкта;
-- колонку d_month,
-- що містить назву місяця відкриття об'єкта;
-- колонку d_day,
-- що містить назву дня тижня відкриття об'єкта.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT name, YEAR(discovery_date) AS d_year, MONTHNAME(discovery_date) AS d_month, DAYNAME(discovery_date) AS d_day
FROM object;