# Using the base Python image for our application
FROM python:3.8-slim

# Setting the working directory in the container
WORKDIR /app

# Copying the application files into the container
COPY app.py .

# Running our application
CMD ["python", "app.py"]