-- IN Operator
--
-- Select all columns from the car table using *,
-- where the brand field value is ONE OF: mazda, toyota, nissan.
-- Use the IN operator.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Оператор IN
--
-- Вибрати з таблиці car всі колонки, використовуючи *,
-- у яких значення поля brand ОДНЕ З: mazda, toyota, nissan.
-- Використовуй оператор IN.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT * FROM car WHERE brand IN ('mazda', 'toyota', 'nissan');