-- LEFT JOIN, Aliases, WHERE, GROUP BY, ORDER BY, and LIMIT
--
-- In this task, you need to:
-- 1. Select the last_name and country columns
-- from the authors table,
-- renaming them to author and author_country respectively.
-- Also select the genre column from the books table,
-- renaming it to book_genre.
-- 2. Join the authors and books tables
-- using the LEFT JOIN operator,
-- renaming them to author and book respectively.
-- 3. Using the ON operator, add a condition
-- that the id column from the authors table
-- is equal to the author_id column from the books table.
-- 4. Using the WHERE operator, add a condition
-- that genre from the books table must be equal to 'fantasy'.
-- 5. Using the GROUP BY operator,
-- group the result by the last_name and country columns
-- from the authors table
-- and by the genre column from the books table.
-- 6. Using the ORDER BY and ASC operators,
-- sort the result by the country column from the authors table.
-- 7. Using the LIMIT operator,
-- add a row limit of 5.
-- Use the LEFT JOIN, AS, ON, WHERE, GROUP BY,
-- ORDER BY, ASC, and LIMIT operators.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- LEFT JOIN, аліаси, WHERE, GROUP BY, ORDER BY і LIMIT
--
-- У цьому завданні тобі буде потрібно:
-- 1. Вибрати колонки last_name і country
-- з таблиці authors,
-- перейменувавши їх на author
-- та author_country відповідно.
-- Також вибрати колонку genre
-- з таблиці books,
-- перейменувавши її в book_genre.
-- 2. Об'єднати таблиці authors і books
-- оператором LEFT JOIN,
-- перейменувавши їх на author та book відповідно.
-- 3. Використовуючи оператор ON,
-- додати умову, що колонка id
-- таблиці authors
-- дорівнює колонці author_id таблиці books.
-- 4. Використовуючи оператор WHERE,
-- додати умову, що genre таблиці books
-- має дорівнювати 'fantasy'.
-- 5. Використовуючи оператор GROUP BY,
-- згрупувати результат за колонками last_name та country
-- таблиці authors
-- і колонкою genre таблиці books.
-- 6. Використовуючи оператори ORDER BY і ASC,
-- відсортувати результат за колонкою country
-- таблиці authors.
-- 7. Використовуючи оператор LIMIT,
-- додати обмеження на кількість рядків у розмірі 5.
-- Використовуй оператори LEFT JOIN, AS, ON, WHERE,
-- GROUP BY, ORDER BY, ASC та LIMIT.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT author.last_name AS author, author.country AS author_country, book.genre AS book_genre
FROM authors AS author
         LEFT JOIN books AS book ON author.id = book.author_id
WHERE book.genre = 'fantasy'
GROUP BY author.last_name, author.country, book.genre
ORDER BY author_country ASC LIMIT 5;