-- Where Are You, Beauties
--
-- Find the location column from the gyms table,
-- and the name and sex columns from the customers table,
-- while replacing the table name gyms with 'gym'
-- and the table name customers with 'visitor'.
-- Use AS for the temporary replacement of names.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Де ж ви є, красуні
--
-- Потрібно знайти колонку location
-- з таблиці gyms,
-- і колонки name та sex
-- з таблиці customers,
-- але водночас замінивши назву таблиці gyms на 'gym',
-- а назву таблиці customers на 'visitor'.
-- Використовуй AS для тимчасової заміни назв.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT gym.location, visitor.name, visitor.sex FROM gyms AS gym, customers AS visitor;