-- IFNULL
--
-- Write a query that uses IFNULL to check null for null
-- and returns 1.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- IFNULL
--
-- Напиши запит, який за допомогою IFNULL
-- перевіряє null на null і повертає 1.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT IFNULL(NULL, 1);