-- IF Inside IF
--
-- Write a query that returns the following text according
-- to the value of the age field in the customers table:
-- 'child' if age is less than or equal to 12,
-- 'adult' if age is greater than or equal to 20,
-- 'teenager' if age is greater than 12 and less than 20.
-- Limit the selection to 5 records.
-- Use a query of the following form:
-- SELECT IF(<condition>, <if_true>, IF(...)) FROM <table> LIMIT ...
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- IF в IF-і
--
-- Напиши запит, який відповідно до значення поля age
-- у таблиці customers повертає наступний текст:
-- 'child', якщо вік менше або дорівнює 12,
-- 'adult', якщо вік більше або дорівнює 20,
-- 'teenager', якщо вік більше 12 і менше 20.
-- Обмеж вибірку 5 записами.
-- Використовуй запит виду:
-- SELECT IF(<умова>, <якщо_істинно>, IF(...)) FROM <таблиця> LIMIT ...
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT IF(age <= 12, 'child', IF(age >= 20, 'adult', 'teenager')) FROM customers LIMIT 5;