-- Born in the First 200 Days
--
-- Write a query that selects the name and department
-- of employees who were born in the first 200 days of the year
-- from the employee table.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Народжені в першій 200-ці
--
-- Напиши запит, який з таблиці employee
-- вибере ім'я name та департамент department
-- співробітників, які народилися
-- у перші 200 днів року.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT name, department FROM employee WHERE DAYOFYEAR(date_of_birth) < 200;