-- Filtering 1
--
-- Get the name column from the part table.
-- Filter the data:
-- only values that contain the string 'Special' are needed.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Фільтрація 1
--
-- Отримай з таблиці part колонку name.
-- Відфільтруй дані:
-- потрібні тільки ті значення,
-- які містять рядок 'Special'.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT name FROM part WHERE name LIKE '%Special%';