# Using the official Python base image
FROM python:3.8-slim

# Setting the working directory
WORKDIR /app

# Copying the Python script into the working directory
COPY app.py .

# Command to be executed when the container starts
CMD ["python", "app.py"]