# Using the minimal Python base image
FROM python:alpine

# Setting the working directory
WORKDIR /app

# Copying the Python application into the container
COPY . .

# Command to run the application
CMD ["python", "app.py"]