-- Strictly Less Than
--
-- Using a database query, compare numbers using the IF function
-- and the < sign, and return 'yes' if the first number
-- is strictly less than the second one, and 'no' otherwise.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Строго менше
--
-- За допомогою запиту до бази даних порівняти числа,
-- використовуючи функції IF та знак <
-- і повернути 'yes', якщо перше число строго менше другого,
-- і 'no' — у протилежному випадку.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT IF(A < B, 'yes', 'no');