# Running Grafana
# Run Grafana and configure the server to start automatically.
# The Grafana web interface must be available at http://localhost:3000.
#
# Requirements:
# • Docker must be used to install and run the container with Grafana, ensuring that it is available for further configuration.
# • The Grafana container must be configured to restart automatically in case of shutdown or system reboot, ensuring its continuous availability.
# • The Grafana web interface must be available at http://localhost:3000, which requires the appropriate Docker port configuration to forward requests to the container.
#
# 🇺🇦 Ukrainian version:
#
# Запуск Grafana
# Запустіть Grafana і налаштуйте автозапуск сервера. Веб-інтерфейс Grafana має бути доступний за адресою http://localhost:3000.
#
# Вимоги:
# • Необхідно використовувати Docker для встановлення та запуску контейнера з Grafana, забезпечуючи його доступність для виконання подальших налаштувань.
# • Контейнер з Grafana має бути налаштований на автоматичний перезапуск у разі зупинки або перезавантаження системи, що забезпечить його постійну доступність.
# • Веб-інтерфейс Grafana має бути доступний за адресою http://localhost:3000, що вимагає відповідного налаштування портів у Docker для перенаправлення запитів до контейнера.

version: '3.8'

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: