-- Adding a FOREIGN KEY to a Table with Options
--
-- Write a script for adding
-- a FOREIGN KEY with the options
-- ON UPDATE CASCADE,
-- ON DELETE SET NULL
-- to the event table
-- on the user_id field
-- with a reference to the ID field
-- of the users table.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Додавання до таблиці FOREIGN KEY з опціями
--
-- Напиши скрипт додавання FOREIGN KEY
-- з опціями ON UPDATE CASCADE,
-- ON DELETE SET NULL
-- до таблиці event
-- за полем user_id
-- із посиланням на поле ID
-- таблиці users.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
ALTER TABLE event ADD FOREIGN KEY (user_id) REFERENCES users(ID) ON UPDATE CASCADE ON DELETE SET NULL;