-- Less Than or Equal?
--
-- Using a database query, compare numbers using the IF function
-- and the <= sign, and return 1 if the first number is less than
-- or equal to the second one, and 0 otherwise.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Менше чи дорівнює?
--
-- За допомогою запиту до бази даних порівняти числа,
-- використовуючи функції IF та знак <=
-- і повернути 1, якщо перше число менше або дорівнює другому,
-- і 0 — у протилежному випадку.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT IF(A <= B, 1, 0);