# Using the base Python image for our application
FROM python:3.9-slim

# Setting the working directory
WORKDIR /app

# Copying the script.py file into the container directory
COPY script.py /app/

# Defining the command that will be executed when the container starts
CMD ["python", "script.py"]