-- Bitwise Inversion
--
-- Write a query that selects the bitwise inversion
-- of the a field
-- from the logic table.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Побітова інверсія
--
-- Напиши запит, який з таблиці logic
-- вибере побітову інверсію поля a.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT ~ a FROM logic;