-- Update 1
--
-- In the publisher table,
-- for the publisher named 'Wordsworth Editions',
-- change the name to 'Author''s Edition'.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Зміна 1
--
-- У таблиці publisher
-- у видавця під назвою 'Wordsworth Editions'
-- зміни назву на 'Author''s Edition'.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
UPDATE publisher SET name = 'Author''s Edition' WHERE name = 'Wordsworth Editions';