-- Long and Short Names
--
-- Write a query that selects the lengths
-- of employee names in bytes and characters
-- from the employee table,
-- based on the name field.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Довгі та короткі імена
--
-- Напиши запит, який із таблиці employee
-- вибере довжини імен name співробітників
-- у байтах та символах.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT LENGTH(name), CHAR_LENGTH(name) FROM employee;