-- How Many Cars Are There?
--
-- Write a query that selects information from the cars table
-- about how many cars of each name are available.
-- The name column in the result must be named car_name,
-- and the count column must be named car_count.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Наскільки багато машин
--
-- Напиши запит, який із таблиці cars вибере інформацію
-- про те, скільки яких назв name автомобілів є в наявності.
-- Колонка з ім'ям у результаті повинна мати назву car_name,
-- а колонка з кількістю — car_count.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT name AS car_name, COUNT(*) AS car_count FROM cars GROUP BY name;