input {
  beats {
    port => 5044
  }
}

filter {
  # Filters for processing logs can be added here if necessary
    json {
        source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]  # Specify the host and port of your Elasticsearch
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
}