# Using the official Python image as the base image
FROM python:3.12-slim

# Setting the working directory inside the container
WORKDIR /app

# Copying the Python script into the working directory
COPY app.py .

# Command to be executed when the container starts
CMD ["python", "app.py"]