-- AND Operator
--
-- Select the contents of all columns from the employee table using *,
-- where the salary field value is strictly less than 5000
-- AND the salary field value is strictly greater than 2000.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Оператор AND
--
-- Вибрати з таблиці employee, використовуючи *,
-- вміст всіх колонок,
-- у яких значення поля salary строго менше 5000
-- І значення поля salary строго більше 2000.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT * FROM employee WHERE salary < 5000 AND salary > 2000;