-- BETWEEN Operator
--
-- Get all objects from the object table
-- in the space schema
-- that were discovered from the beginning of 2010
-- to the end of 2020.
-- The result must contain all columns of the table.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Оператор BETWEEN
--
-- Отримай з таблиці object,
-- схема space,
-- всі об'єкти,
-- відкриті з початку 2010
-- до кінця 2020 року.
-- Результат повинен містити усі колонки таблиці.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT * FROM object WHERE YEAR(object.discovery_date) BETWEEN 2010 AND 2020;