-- IFNULL with Text
--
-- Write a query that uses IFNULL to check null for null
-- and returns 'yes'.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- IFNULL з текстом
--
-- Напиши запит, який за допомогою IFNULL
-- перевіряє null на null і повертає 'yes'.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT IFNULL(NULL, 'yes');