-- String Functions 2
--
-- Get numbers and names
-- from the lego_set table
-- as one column named full_name
-- according to this principle:
-- if the number was 71761,
-- and the name was 'Zane’s Power Up Mech EVO',
-- then the full_name column must contain:
-- 71761, Zane’s Power Up Mech EVO
-- That is, the number and the name
-- are separated by a comma and a space.
-- Sort the result by the length of name
-- in ascending order.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Рядкові функції 2
--
-- Отримай з таблиці lego_set
-- номери та імена
-- у вигляді однієї колонки з ім'ям full_name
-- за принципом:
-- якщо номер був 71761,
-- а ім'я — 'Zane’s Power Up Mech EVO',
-- в колонці full_name має вийти:
-- 71761, Zane’s Power Up Mech EVO
-- Тобто, номер та ім'я
-- розділені комою та пробілом.
-- Відсортуй результат за довжиною name
-- у порядку зростання.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT CONCAT(number, ', ', name) AS full_name FROM lego_set ORDER BY LENGTH(name);