-- LIMIT Operator
--
-- Select all columns from the car table using *.
-- Only the first eleven records must be selected.
-- The LIMIT operator must be used.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- Оператор LIMIT
--
-- Вибрати всі колонки з таблиці car, використовуючи *.
-- Вибрати потрібно лише перших одинадцять записів.
-- Потрібно використовувати: LIMIT.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT * FROM car LIMIT 11;