-- JOIN, Aliases, WHERE, GROUP BY, and ORDER BY
--
-- In this task, you need to:
-- 1. Select the sex and country columns
-- from the authors table,
-- renaming them to author_sex and author_country respectively.
-- Also select the copies_sold_millions column
-- from the books table
-- and rename it to books_sold.
-- 2. Join the authors and books tables
-- using the JOIN operator,
-- renaming them to a and b respectively.
-- 3. Using the ON operator, add a condition
-- that the author_id column from the authors table
-- is equal to the author_id column from the books table.
-- 4. Using the WHERE operator, add a condition
-- that copies_sold_millions from the books table
-- must be greater than 10.
-- 5. Using the GROUP BY operator,
-- group the result by the sex and country columns
-- from the authors table
-- and by the copies_sold_millions column from the books table.
-- 6. Using the ORDER BY and DESC operators,
-- sort the result in descending order
-- by the copies_sold_millions column from the books table.
-- Use the JOIN, AS, ON, WHERE, GROUP BY, ORDER BY, and DESC operators.
--
-- Requirements:
--
-- 1. The query must be implemented according to the task condition.
--
-- 🇺🇦 Ukrainian version:
--
-- JOIN, аліаси, WHERE, GROUP BY і ORDER BY
--
-- У цьому завданні тобі буде потрібно:
-- 1. Вибрати колонки sex і country
-- з таблиці authors,
-- перейменувавши їх на author_sex
-- і author_country відповідно.
-- Також вибрати колонку copies_sold_millions
-- з таблиці books
-- та перейменувати її на books_sold.
-- 2. Об'єднати таблиці authors і books
-- оператором JOIN,
-- перейменувавши на a і b відповідно.
-- 3. Використовуючи оператор ON,
-- додати умову, що колонка author_id
-- таблиці authors
-- дорівнює колонці author_id таблиці books.
-- 4. Використовуючи оператор WHERE,
-- додати умову, що copies_sold_millions
-- таблиці books має бути більше 10.
-- 5. Використовуючи оператор GROUP BY,
-- згрупувати результат за колонками sex та country
-- таблиці authors
-- та колонкою copies_sold_millions таблиці books.
-- 6. Використовуючи оператори ORDER BY і DESC,
-- відсортуй результат за спаданням
-- за колонкою copies_sold_millions таблиці books.
-- Використовуй оператори JOIN, AS, ON, WHERE, GROUP BY,
-- ORDER BY та DESC.
--
-- Вимоги:
--
-- 1. Запит має бути реалізований згідно з умовою.

-- Write your code here:
SELECT a.sex AS author_sex, a.country AS author_country, b.copies_sold_millions AS books_sold
FROM authors AS a
         JOIN books AS b ON a.author_id = b.author_id
WHERE b.copies_sold_millions > 10 GROUP BY author_sex, author_country, books_sold ORDER BY books_sold DESC;